[project]
name = "paleo-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ben Pedigo", email = "benjamindpedigo@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
paleo-analysis = "paleo_analysis:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
